### PR TITLE
Add "begins with one of" and "does not begin with one of" operators for string input types

### PR DESCRIPTION
**Pull request by bluec**
This is useful especially if you wish to compare the beginning of the postcode for surcharge areas, 

e.g. Entire Postal Code "begins with one of" "IV212,IV232,PA487"

### CODE REVIEW

**Review by punkstar — APPROVED** [review]

**Comment by punkstar** [comment]
nice

**Comment by bluec** [comment]
Thanks @punkstar would be cool if you can put a new release out with a version bump.

**Comment by bluec** [comment]
Again @punkstar any chance of a new release and version bump?

**Comment by punkstar** [comment]
Done.

**Pull request merged**
